[package]
name    = "simple_proxy"
version = "0.1.0"
authors = ["Terry Raimondo <terry.raimondo@gmail.com>", "Thibaut Roche <thibaut.roche.perso@gmail.com>"]
description = "Simple proxy with middlewares, easy to customize, easy to use."
license = "Apache-2.0"

[features]
router = ["regex"]

[dependencies]
futures        = "0.1.21"
http           = "0.1.5"
failure        = "0.1.1"
failure_derive = "0.1.1"
log            = "0.4.1"
chrono         = "0.4.2"
regex          = { version = "1.0.0",  optional = true }
rand           = "0.5.0"
mockers        = "0.11.1"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"

[dev-dependencies]
mockers_derive = "0.11.1"
