[package]
name    = "simple_proxy"
version = "0.1.3"
authors = ["Terry Raimondo <terry.raimondo@gmail.com>"]
description = "Simple proxy with middlewares, easy to customize, easy to use."
license = "Apache-2.0"
homepage = "https://github.com/terry90/rs-simple-proxy"
repository = "https://github.com/terry90/rs-simple-proxy"

[package.metadata.docs.rs]
features = ["docs"]

[features]
router = ["regex"]
docs   = ["router"]

[dependencies]
futures        = "0.1.21"
log            = "0.4.2"
chrono         = { version = "0.4.3", features = ["serde"] }
regex          = { version = "1.0.0", optional = true }
rand           = "0.5.1"
serde_json     = "1.0.20"
serde_derive   = "1.0.66"
serde          = "1.0.66"
hyper          = "0.12.1"
http           = "0.1.6"