[package]
name = "simple_proxy"
version = "0.1.0"
authors = ["Terry Raimondo <terry.raimondo@gmail.com>"]

[dependencies]
futures = "0.1.21"
http = "0.1.5"
oauth2 = "1.3.0"
dotenv = "0.11.0"
structopt = "0.2.8"
clap = "2.31.2"
failure = "0.1.1"
failure_derive = "0.1.1"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"
