[package]
name    = "simple_proxy"
version = "0.1.0"
authors = ["Terry Raimondo <terry.raimondo@gmail.com>"]
description = "Simple proxy with middlewares, easy to customize, easy to use."
license = "Apache-2.0"

[features]
router = ["regex"]

[dependencies]
futures        = "0.1.21"
http           = "0.1.5"
log            = "0.4.2"
chrono         = { version = "0.4.2", features = ["serde"] }
regex          = { version = "1.0.0", optional = true }
rand           = "0.5.0"
serde          = "1.0.66"
serde_derive   = "1.0.66"
serde_json     = "1.0.19"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"
