[package]
name    = "simple_proxy"
version = "0.1.1"
authors = ["Terry Raimondo <terry.raimondo@gmail.com>"]
description = "Simple proxy with middlewares, easy to customize, easy to use."
license = "Apache-2.0"
homepage = "https://github.com/terry90/rs-simple-proxy"
repository = "https://github.com/terry90/rs-simple-proxy"

[features]
router = ["regex"]

[dependencies]
futures        = "0.1.21"
log            = "0.4.2"
chrono         = { version = "0.4.2", features = ["serde"] }
regex          = { version = "1.0.0", optional = true }
rand           = "0.5.1"
serde_json     = "1.0.20"
hyper          = "0.12.1"
